# Generated by Django 3.1 on 2020-08-24 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('contact', models.CharField(max_length=50, verbose_name='contact')),
                ('password', models.CharField(max_length=25, verbose_name='password')),
                ('vehicle_number', models.CharField(max_length=50, verbose_name='vehicle_number')),
                ('rc_image', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='order_id')),
                ('payment_method', models.CharField(max_length=25, verbose_name='payment_method')),
            ],
        ),
        migrations.CreateModel(
            name='PizzaMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_mania', models.CharField(max_length=25, verbose_name='pizza_mania')),
                ('size', models.CharField(max_length=25, verbose_name='pizza_mania')),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chilli_flakes', models.CharField(max_length=25, null=True, verbose_name='chilli_flakes')),
                ('organic_seasons', models.CharField(max_length=25, null=True, verbose_name='organic_seasons')),
                ('cheese_cubes', models.IntegerField(verbose_name='garlic_cheese')),
                ('black_olives', models.IntegerField(verbose_name='black_olives')),
                ('other_instructions', models.CharField(max_length=25, verbose_name='other_instructions')),
            ],
        ),
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False, verbose_name='Email')),
                ('contact', models.CharField(max_length=50, verbose_name='contact')),
                ('password', models.CharField(max_length=25, verbose_name='password')),
                ('address', models.CharField(max_length=100, verbose_name='address')),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, verbose_name='token')),
                ('time_and_date_track', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userregister')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('delivery_address', models.CharField(max_length=25, verbose_name='delivery_address')),
                ('tracking_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='tracking_id')),
                ('delivery_person', models.CharField(max_length=25, verbose_name='delivery_person')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.paymentdetails')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, verbose_name='token')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employeeregister')),
            ],
        ),
    ]
