# Generated by Django 3.1 on 2020-08-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200825_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='token',
            field=models.CharField(max_length=200, verbose_name='token'),
        ),
    ]
