# Generated by Django 3.1 on 2020-08-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200825_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzamenu',
            name='price',
            field=models.IntegerField(null=True, verbose_name='price'),
        ),
    ]
