# Generated by Django 3.1 on 2020-08-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_pizzamenu_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzamenu',
            name='price',
            field=models.IntegerField(verbose_name='price'),
        ),
    ]
