# Generated by Django 3.1 on 2020-08-31 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200825_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='topping',
            name='garlic_cheese',
            field=models.IntegerField(default=None, verbose_name='garlic_cheese'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topping',
            name='cheese_cubes',
            field=models.IntegerField(verbose_name='cheese_cubes'),
        ),
    ]
