# Generated by Django 3.1 on 2020-08-31 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200831_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topping',
            name='chilli_flakes',
            field=models.IntegerField(null=True, verbose_name='chilli_flakes'),
        ),
        migrations.AlterField(
            model_name='topping',
            name='organic_seasons',
            field=models.IntegerField(null=True, verbose_name='organic_seasons'),
        ),
    ]
